apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: echo
  namespace: flux-system
spec:
  image: ghcr.io/huangyingting/echo
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: echo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: echo
  policy:
    semver:
      range: 0.x