creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(client-secret|clientID|subscriptionID|tenantID|resourceGroupName|hostedZoneName|email|commonName|dnsNames|hosts)$
    pgp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
