apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:cAwoA1jpMBbwcJRxbrDexUGLR4NxjaxqrBaGVKYCzsPDfMadjJHZNXFCAKhq+yjC,iv:yeFTFRxU7A8P4DZACXBc8l7LgVj2Pi+b5K6LNfOEsrU=,tag:VDHXUaWVpo4r6Iv+XduDXw==,type:str]
    client_secret: ENC[AES256_GCM,data:fc6Syd5Setonnc1rT1xnWIkzz3E4KOf76UAGzXfGWiriFpDrVsd/ssKELodbo4m9Ki7icj8L+NU=,iv:cyeb38M4VEud/rV4u1emmcNcsSe52AYVvT7k+LNHajU=,tag:3H0xlpy8J1NYp1KUx75Yaw==,type:str]
    endpoint: ENC[AES256_GCM,data:xmGPLcsXtUnsoilXklZI4OYerAaq8RwtmePczSlKnFxM9usdMgXQAujOJocQGKn+PP5B+KZyC/lusJUKXHAuTqZ549ZGpqv6cMr7MgJlbY9E2rINZnHhoDkyZu4OFiU3E8wAGg==,iv:H3ZDf/z0cA8vUF95wRLyciNh5hpiw/aRBC4nNESWLK4=,tag:4k1XAC3YKbpnv7kKAzoSfw==,type:str]
    random_secret: ENC[AES256_GCM,data:Ef2p7jb+Rv/BB8LGMIWlh6KUlwEk5jhD,iv:RGbhc+Dqq9ZKilRJHvtpWYY+/8vbXJ0HawetKHpeq0o=,tag:8TV12hmWbqxePZHZ2WjsZg==,type:str]
kind: Secret
metadata:
    name: azuread
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-31T08:28:05Z"
    mac: ENC[AES256_GCM,data:PhC5B/K60XrfJ4IlKSCttj9ebKAXXJl6IiYXYPYT2JHUfgcGQ40Z9kRqDx32/DulZEAlO4yixWYN3lXa7fe1D5FR2b2xEqEMyKfNpxtYh6U4ElPzWmAt8MDG2cwp8NyAYmZmhC1+5coKMstORbInrccpcrbC4obj0M8nZ1X4IGM=,iv:sBWAMV7LI1fgYReg051JlW1JXBeYSUFemEc4eEU3fxs=,tag:OA6wecN9in/Z2hhC93+8ww==,type:str]
    pgp:
        - created_at: "2022-12-31T08:28:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMARAAnRwzf/gmSxAetgTqkLSO760N2iKlrDyRG4rlbBwUAqrX
            Y5GhKvhKQUr2tjXVgoVNiGbsgfl7HeIqadDFAGZKiEuQU2KvElHwBtzZar44kRE1
            LDhnHo+9tzyLNk4LfMpGj7OIZxz7EJqKxNG0yVuy4okkmla8Xe0NSStplCniK0ce
            genFxrbrrjombFAoZhpqz4Kzd5K/UEHyYKkwm9cN4OYxtmxGX+e8Pr50NEedASrV
            eLZmM6gOZmDV6fEpEBdrEcDZV66i1zgvxC0JED3jj43z+nZf6RCjPRlzlHz071iw
            bJYVzGbcmZwb2/vECWE5VysObtJ02Ypnl5iWcg5pEFjfpD/O9J4FGsd+Jqq6sZQs
            3lI/7uHluCZrbGKqgONY/vnHoxNFXnUFt2WQg7Y81iC7OyI+6mGd1cG22lMBpW4H
            TH8+gmNThqJsmDZ10Qzk+odUUjZ5ZdXKrvTrt+DXKDl8g2ULEwJvayojAskpUkyH
            98pgo14UZvrfG+RjCejvJzblPh3vYLxMRmmDghseMxsd9L0MKtswDHh+rVMbvYmL
            Vx2OmQsip6a5/RVybHuIcIsAN86y96jh4OGafzes9NkAtCLvfhCzqDB+oEM6YsS8
            UUVXGASR2YyqJI1euNa4ezlykLLuuJg2RIWhFNmgshhGvizVSwQ26ta0k97GfZbS
            XAGfjbvqE/AUgdgy86MO8Ek3qGImgDyETCFWLNA7EaGsOZqC5MvkpuIYgmZh5TRh
            OaSE6ip6+8Z5v/iA2WGRmv8NokkuU7cVWnbB9GyMOFk6yie5nOXNmUBhmbg8
            =cQo4
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(host|hosts|client_id|client_secret|endpoint|random_secret)$
    version: 3.7.3
