apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1  
  metadata:
    - name: connectionString
      secretKeyRef:
        name: reddog-sb
        key: sb-connect-string
scopes:
  - order-service
  - make-line-service
  - loyalty-service
  - receipt-generation-service
  - accounting-service
auth:
  secretStore: reddog.secretstore