apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulsar
resources:
  - ../../base/pulsar
secretGenerator:
  - name: pulsar-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
