apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo
bases:
  - ../../base/echo
patchesStrategicMerge:
  - ingress.enc.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: echo
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
