creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(host|hosts|ORDER_QUEUE_USERNAME|ORDER_QUEUE_PASSWORD|AZURE_OPENAI_DEPLOYMENT_NAME|AZURE_OPENAI_ENDPOINT|OPENAI_API_KEY)$
    pgp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
