apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadtester
spec:
  releaseName: loadtester
  chart:
    spec:
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3