apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - slack.yaml
  - ingress.yaml
  - receiver.yaml
  - networkpolicy.yaml
configurations:
  - kustomizeconfig.yaml
secretGenerator:
  - name: webhook-token
    envs:
      - webhook-token.env