creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(DATABASE_DATASOURCE|name|tlsHosts|nginx\.ingress\.kubernetes\.io\/auth-url|nginx\.ingress\.kubernetes\.io\/auth-signin)$
    pgp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
