apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-workload-identity-system
resources:
  - namespace.yaml
  - release.yaml
secretGenerator:
  - name: workload-identity-webhook-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
