apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-identity-webhook
spec:
  releaseName: workload-identity-webhook
  chart:
    spec:
      chart: workload-identity-webhook
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: workload-identity-webhook-values
