apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
spec:
  releaseName: linkerd-viz
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "30.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
