apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapp
    name: chat-copilot-webapp
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapp
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapp
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapp-nginx:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapp
                  ports:
                    - containerPort: 3000
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T07:05:47Z"
    mac: ENC[AES256_GCM,data:QyV66VN2m1imjmlYjc0pKAb673YG5QCtPJ/u+CdVDuIEyIQpjv6FNgJDW+mnLmb6cAJPg7NrojR2nkTMvd5helAyCu1Ty6YG04fC2IhLwjYpTjJhrtj978EumiPmEaXOBwqegz92M8ddTP4wAfH1iJDugZkIimJiergA+0pm0ns=,iv:61CDWls1KxTOZHwFl838SqiBsuuWPc9hkv3Q84Cfj7o=,tag:dE4aStQ9uNuwBYkTQ9mBNw==,type:str]
    pgp:
        - created_at: "2023-10-16T07:05:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ//VMCo+RSOiBdJvHmSCYtHLxlmRNK/3yhj2W6X2QeO/uMz
            o9YJ/SCUCDfrMKxx3S2kcbEbDn71wEliEqcjpVM6ZQhHrXOeEjMM0zXiVg9UDEuD
            G/kcMWTXzKflwLjt245f/p5T67cZthdbYdKOwBwS3ehMX7BfKpQDH3Gh3hX58jcc
            iWoutaUvEKCGc+21YCegNuBqKleR4aOtImm8dW3Zj+xr3w7D+/XsTdssoSrbc8rA
            /LE3F1/EljJskbXjmadpb81XO+0XU7mSOmRlDjY1sRSent7DLqjdg9G5msRLwcw4
            RC9WHprJH1w215H20pWIr/iwYgAIx08ZHzN1H22Fes0NFkITUU/FgPC2r+G4NBas
            cim3g+m/mn449QtJvwy50NAosJFTd9ktJd5SwK7gkrMDEwxMqujMOLf7RQyuGKZm
            06+nFw3k5jPX6muP2iS2O0eaux59yr8v4ZikvaltS3NW+zC4Jl2qMpIFMqq34fgs
            5Z/x1gQHv74OvIKiW/gwBzbss+PECFq97SSFMh6mFLiicqbTdmLzU1JOUhmqaRqC
            UnQ09L0d8lBucXzPVtF+fJ2IeOjuw4G2Pe6YQEnTSHq9Q94TuDOT3Z16ZaVAIdor
            S9v97AxPi7vkoL+yiwZJcuoQuUopaA8Zd8HkEWdrv/rxevw68qy9NNpPRuet/0vS
            XgFfWbp/h5SvTCn2uK9os8dewcDssj3keOp+ImY4IYi7f1TRe8jrIaMK8fmFuZTe
            ccqstDV2lJD5rqWtaCxQYabIJGWm4Ok5rYHjFA3m6pJzA4N2MgH/ytweZxCNieM=
            =JX9D
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapi
    name: chat-copilot-webapi
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapi
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapi
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapi:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapi
                  env:
                    - name: Authentication__Type
                      value: ENC[AES256_GCM,data:l43moodbmQ==,iv:8sMfP30w2Xzbjz30reGowiNwTc5y/oaDETmtgNyAu0M=,tag:mc4u5OjtEnFN47Owu/03Gg==,type:str]
                    - name: SemanticMemory__Services__Qdrant__Endpoint
                      value: ENC[AES256_GCM,data:NB9IrEgkQORMSKYm0XndSMQ8z+TFP+qa5w==,iv:brvLxsqfs3UXURceI5FZWG5im6gcZrB41/mZ3eyEjN4=,tag:emOn/gJSF0uzmROIe88IrQ==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Host
                      value: ENC[AES256_GCM,data:ggeN77wbQpoGsxg2Gcupz+4=,iv:ohbSyZCanByTMOvOBSaB+XUFWzP7tj/ZGU9nZ2d6MoA=,tag:hijtUqAYujoofdr+az5ePg==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Port
                      value: ENC[AES256_GCM,data:wpzqcw==,iv:NjM3JUZ81qON+rdmjjSiXHLlpNIU1WOF2rFmAt9RGI0=,tag:3RRwEzwNV4MWTgOrIY9foQ==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Username
                      value: ENC[AES256_GCM,data:VRS5AP1uNjg=,iv:9r72R1ceiqy/0TXjewbMwBGq3p4/eZ4mVHZEVqdcwTo=,tag:uPbk1aAhLn+22bWi3A+WVA==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Password
                      value: ENC[AES256_GCM,data:9KUv2rMal4U=,iv:2JQncuDf5wW3F1/b59DeZWsjbXdwRs8k2pywyuV6tu8=,tag:49e7/vabP4P+gU3B+4UEAQ==,type:str]
                    - name: SemanticMemory__ContentStorageType
                      value: ENC[AES256_GCM,data:RwpQJ+zbhAfr3B8k/Ne4+jM=,iv:zgSE41hha7d8Kt6aWp2R2doYk8vKth4IkFIZBJV8j+Q=,tag:6Wf0F6JF4f/xyvYSsESFfg==,type:str]
                    - name: SemanticMemory__ImageOcrType
                      value: ENC[AES256_GCM,data:P9Ek5N6NXIzl,iv:icm2i9wsQBheKGzyy94kxc2OWGZvVmE3v0UaXZy8TIQ=,tag:5oQMZTHM2vL5SnMv4KfMnQ==,type:str]
                    - name: SemanticMemory__TextGeneratorType
                      value: ENC[AES256_GCM,data:6wzhKE5TyfvQBZ0=,iv:BBGklXRwvb4qQUthH4biAPDB7k5v5dr3E79jF8mlU1A=,tag:gCdqaQzSY9+KfizA7cN3LQ==,type:str]
                    - name: SemanticMemory__DataIngestion__DistributedOrchestration__QueueType
                      value: ENC[AES256_GCM,data:cbhZb3lkCVU=,iv:p84UnSL5Tf5s88SXtvEjAke/ULb7EFpsSL/2uFGtoGo=,tag:284NPw0C/5nebAFOKLp+PA==,type:str]
                    - name: SemanticMemory__DataIngestion__VectorDbTypes__0
                      value: ENC[AES256_GCM,data:HZGZ28Z+,iv:8CgS8zZp6iJH3A+lYCIWZx6R/KAIYGsVA8iCQSHjNT4=,tag:eVSVdVR4CrIKzkElmQW5Lg==,type:str]
                    - name: SemanticMemory__DataIngestion__EmbeddingGeneratorTypes__0
                      value: ENC[AES256_GCM,data:f2u4JfPgfymgH08=,iv:f3l8cZpncTbRibzRIffk76SX9rnapX4zT0OFrPdmke8=,tag:bHFDu1VFDX+NlSpB6ffbxA==,type:str]
                    - name: SemanticMemory__Retrieval__EmbeddingGeneratorType
                      value: ENC[AES256_GCM,data:0OF7YfHVC8vHoss=,iv:RwYLUkxuWzcuQN1g0bdf7JR7bpK+902KLDWVJnxHHfs=,tag:Xde3hsQi+7bdlRSwCVePoA==,type:str]
                    - name: SemanticMemory__Retrieval__VectorDbType
                      value: ENC[AES256_GCM,data:AkLVcJmV,iv:084VCp0p6O/2UZNcAFgtoLzWfutPfOnmMMgosl+YLf0=,tag:pjqLlR1zWmsPnxvbkDWLVQ==,type:str]
                    - name: Plugins__1__Name
                      value: ENC[AES256_GCM,data:zp4nZKllWhDQftg=,iv:O3dVJcflfRIYpHaoioyB73CRh2f0FBFLfS5M+weQ5fs=,tag:5Op2C5fQf8JsRNP0fX4eqw==,type:str]
                    - name: Plugins__1__ManifestDomain
                      value: ENC[AES256_GCM,data:vTbt3edlvhsV4yskHdNbzutt/3aVOyf36E+PFfmzWn/9S+HVwH5dabkZixF9xs5Xtw==,iv:0MfcyLsPxqMLgk+8m3HWd+W2+8/BZkT0GBhg3HWnU5g=,tag:eVUI50Xn3NZit40ekFgTyw==,type:str]
                    - name: Plugins__1__Key
                      value: ENC[AES256_GCM,data:cuiHiLZK61o21cIHVhHK25kWPQ9tWnJAlE65+B1PHDFUm4DibxGqSrO8miY=,iv:AAqDvyJYDM8ZQxKHBK+zPUCRWbqVyE0bIvVWGc1grY4=,tag:yAkCwiGJpObgyDUoA/05fg==,type:str]
                    - name: Authentication__AzureAd__ClientId
                      value: ENC[AES256_GCM,data:30ylfr9CXbex5UD4lXwoI4v1Mt0NoELhPTkONad079jkZWaV,iv:hlDlmXJCjMWFSkHKxtDd5gfAHwTYFq37K/5qavXDMBI=,tag:1zIC2wKJjd9AAOQugLAZXg==,type:str]
                    - name: Authentication__AzureAd__TenantId
                      value: ENC[AES256_GCM,data:PLD/vvEaF8UpriEnnsC8Tp6lxJ7PY8+wMSKe8u1X5qfP+JzN,iv:MI7VILI5PC/caQ+pP1FNr2FWy2ibwUW7QNZXaXpEYcM=,tag:L5mgnW2dTR5SfIkgY8ovTA==,type:str]
                    - name: Frontend__AadClientId
                      value: ENC[AES256_GCM,data:9iQyBX2gr/z1fhZqESrSwF2qS7LuixCZMotz6HlfzS8n74+B,iv:qIMvGbqUfEJy7Jysbs6sqsc7OnrLwNCSom5pb/ykSQM=,tag:tOfd/kJfxgDPvRJOE1Lq5w==,type:str]
                    - name: AzureSpeech__Region
                      value: ENC[AES256_GCM,data:xzsxD6dD34lF,iv:GcU1UvHp3HEysELD++0sPrNtLdl9Za/fMTQCDOI+awU=,tag:DMMiGVjgj7wIRnEldw5tZg==,type:str]
                    - name: AzureSpeech__Key
                      value: ENC[AES256_GCM,data:caPuf+9YJty2iV4tqJe64nHwpU8LtB+4ltw7ESAQqG0=,iv:ke3CfcdUkjVK87ZKTfuptP1o9Wvj2rc5SzQBB+Wsj4M=,tag:roEext8Y/lueim5jnDqHJw==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Deployment
                      value: ENC[AES256_GCM,data:57jLkBzvXxQIyxCn+oCeCA21dkiKyw==,iv:GcR4KmILrbVzGuXvoh8l04tRF3YBfvTp8IscRVHbZO8=,tag:6vcFy6MhGW3kYX5+xnUHRg==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Endpoint
                      value: ENC[AES256_GCM,data:urkZq2E22omo14+n7V32dHc9XvOIQWHr+SgaREdnrJ5yCQ==,iv:+bCQjZEYcYbtfyWQ+VDdSbDjo90XXVUVWpdXKAHqJ+Y=,tag:m7aGS3vIcoujLnaPM0+32w==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__APIKey
                      value: ENC[AES256_GCM,data:qeggjEt58zmvuv0f+MjU9KT6J4DI61Igm7YoEZqfQuo=,iv:v2bz2CQknfTtpZ5ucigHT1ijfxoc1U3xGFb5u3dWii8=,tag:Zs1b0S0F7oBcwTLV/NpdtA==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Deployment
                      value: ENC[AES256_GCM,data:5iRtLQ/+OekigyFG,iv:/yVLN4RH8KB9VD5PFtID1q9YZo0ArHXPQQSkOue1h9s=,tag:3QfSsGhJ4Odnpggzqt/lLw==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Endpoint
                      value: ENC[AES256_GCM,data:g05olhHsxDrqBpX1Y0Yzu4R6MeSfxQDo0Km4BdgsO8KvoA==,iv:67RYhGwvWtV6aZ7V0NtrmJEAaXo/Yl+3oE7Oqj8N3ro=,tag:P//g5a6yaQLs9ZsYSRiBKw==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__APIKey
                      value: ENC[AES256_GCM,data:WhytibpFwU1qw5MDMKtkXPCjWCPAK+yBbqMS7aUghT4=,iv:RH0B7SJLpO/x1k5ylQTSeDoc8dFAlO7feV1ykbrxlto=,tag:Tu6OfOJdZhb5yuozra1e6g==,type:str]
                    - name: AllowedOrigins__0
                      value: ENC[AES256_GCM,data:fuMNA9Yo1v4B5QG09iCqtlkdHMF9jDyLHZnUsHYUfX5jMS21ppRw1He5,iv:yd5/6Ns5AD3C1KxtXXElENH+fAh73aBcYuW2q7iAbFw=,tag:u155fRVftxV3GCPclbErSg==,type:str]
                    - name: AllowedOrigins__1
                      value: ENC[AES256_GCM,data:q+RcrpxBFcDfXxja7xBHMHg9xPNcsqJmWz4fzujZUEXOvR6sTu+Gl8xtdQ==,iv:1osZWWBuKCgtTt/KgCT+M8lZdguMzyPfS4JjItSLsCs=,tag:sVSUxfUf+WA1pnKUgBvQ+A==,type:str]
                  ports:
                    - containerPort: 8080
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T07:05:47Z"
    mac: ENC[AES256_GCM,data:QyV66VN2m1imjmlYjc0pKAb673YG5QCtPJ/u+CdVDuIEyIQpjv6FNgJDW+mnLmb6cAJPg7NrojR2nkTMvd5helAyCu1Ty6YG04fC2IhLwjYpTjJhrtj978EumiPmEaXOBwqegz92M8ddTP4wAfH1iJDugZkIimJiergA+0pm0ns=,iv:61CDWls1KxTOZHwFl838SqiBsuuWPc9hkv3Q84Cfj7o=,tag:dE4aStQ9uNuwBYkTQ9mBNw==,type:str]
    pgp:
        - created_at: "2023-10-16T07:05:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ//VMCo+RSOiBdJvHmSCYtHLxlmRNK/3yhj2W6X2QeO/uMz
            o9YJ/SCUCDfrMKxx3S2kcbEbDn71wEliEqcjpVM6ZQhHrXOeEjMM0zXiVg9UDEuD
            G/kcMWTXzKflwLjt245f/p5T67cZthdbYdKOwBwS3ehMX7BfKpQDH3Gh3hX58jcc
            iWoutaUvEKCGc+21YCegNuBqKleR4aOtImm8dW3Zj+xr3w7D+/XsTdssoSrbc8rA
            /LE3F1/EljJskbXjmadpb81XO+0XU7mSOmRlDjY1sRSent7DLqjdg9G5msRLwcw4
            RC9WHprJH1w215H20pWIr/iwYgAIx08ZHzN1H22Fes0NFkITUU/FgPC2r+G4NBas
            cim3g+m/mn449QtJvwy50NAosJFTd9ktJd5SwK7gkrMDEwxMqujMOLf7RQyuGKZm
            06+nFw3k5jPX6muP2iS2O0eaux59yr8v4ZikvaltS3NW+zC4Jl2qMpIFMqq34fgs
            5Z/x1gQHv74OvIKiW/gwBzbss+PECFq97SSFMh6mFLiicqbTdmLzU1JOUhmqaRqC
            UnQ09L0d8lBucXzPVtF+fJ2IeOjuw4G2Pe6YQEnTSHq9Q94TuDOT3Z16ZaVAIdor
            S9v97AxPi7vkoL+yiwZJcuoQuUopaA8Zd8HkEWdrv/rxevw68qy9NNpPRuet/0vS
            XgFfWbp/h5SvTCn2uK9os8dewcDssj3keOp+ImY4IYi7f1TRe8jrIaMK8fmFuZTe
            ccqstDV2lJD5rqWtaCxQYabIJGWm4Ok5rYHjFA3m6pJzA4N2MgH/ytweZxCNieM=
            =JX9D
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-web-searcher
    name: chat-copilot-web-searcher
spec:
    selector:
        matchLabels:
            app: chat-copilot-web-searcher
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-web-searcher
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-web-searcher:main
                  imagePullPolicy: Always
                  name: chat-copilot-web-searcher
                  env:
                    - name: PluginConfig__BingApiKey
                      value: ENC[AES256_GCM,data:uteeqWEPdHh6YGM8HH3HUA2ZPv9G1v3GK/zOfV2Aunc=,iv:N47h7cO+Q4JhzMJUo1YC3bqBTAKLQAs3uNljAwhHhIQ=,tag:GnQmg6M463/ZNRucyIHY4A==,type:str]
                  ports:
                    - containerPort: 80
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T07:05:47Z"
    mac: ENC[AES256_GCM,data:QyV66VN2m1imjmlYjc0pKAb673YG5QCtPJ/u+CdVDuIEyIQpjv6FNgJDW+mnLmb6cAJPg7NrojR2nkTMvd5helAyCu1Ty6YG04fC2IhLwjYpTjJhrtj978EumiPmEaXOBwqegz92M8ddTP4wAfH1iJDugZkIimJiergA+0pm0ns=,iv:61CDWls1KxTOZHwFl838SqiBsuuWPc9hkv3Q84Cfj7o=,tag:dE4aStQ9uNuwBYkTQ9mBNw==,type:str]
    pgp:
        - created_at: "2023-10-16T07:05:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ//VMCo+RSOiBdJvHmSCYtHLxlmRNK/3yhj2W6X2QeO/uMz
            o9YJ/SCUCDfrMKxx3S2kcbEbDn71wEliEqcjpVM6ZQhHrXOeEjMM0zXiVg9UDEuD
            G/kcMWTXzKflwLjt245f/p5T67cZthdbYdKOwBwS3ehMX7BfKpQDH3Gh3hX58jcc
            iWoutaUvEKCGc+21YCegNuBqKleR4aOtImm8dW3Zj+xr3w7D+/XsTdssoSrbc8rA
            /LE3F1/EljJskbXjmadpb81XO+0XU7mSOmRlDjY1sRSent7DLqjdg9G5msRLwcw4
            RC9WHprJH1w215H20pWIr/iwYgAIx08ZHzN1H22Fes0NFkITUU/FgPC2r+G4NBas
            cim3g+m/mn449QtJvwy50NAosJFTd9ktJd5SwK7gkrMDEwxMqujMOLf7RQyuGKZm
            06+nFw3k5jPX6muP2iS2O0eaux59yr8v4ZikvaltS3NW+zC4Jl2qMpIFMqq34fgs
            5Z/x1gQHv74OvIKiW/gwBzbss+PECFq97SSFMh6mFLiicqbTdmLzU1JOUhmqaRqC
            UnQ09L0d8lBucXzPVtF+fJ2IeOjuw4G2Pe6YQEnTSHq9Q94TuDOT3Z16ZaVAIdor
            S9v97AxPi7vkoL+yiwZJcuoQuUopaA8Zd8HkEWdrv/rxevw68qy9NNpPRuet/0vS
            XgFfWbp/h5SvTCn2uK9os8dewcDssj3keOp+ImY4IYi7f1TRe8jrIaMK8fmFuZTe
            ccqstDV2lJD5rqWtaCxQYabIJGWm4Ok5rYHjFA3m6pJzA4N2MgH/ytweZxCNieM=
            =JX9D
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
