apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapp
    name: chat-copilot-webapp
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapp
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapp
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapp-nginx:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapp
                  ports:
                    - containerPort: 3000
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:26:12Z"
    mac: ENC[AES256_GCM,data:jpm09FEreziDgTuaxvPnPj0H9VhAKA9dgJP8ZF3rmAL0AlJ1x9GTpK5TaghcBvM5aKgPcoSdziWwbZb+HXNpTQROYAMmTxV5SbriQrFGTg7rR6XKu4k5TJvXxttbfRdxcIqpbv3ZJxCd6JSh31oM4EckngdIohaT1EwR5pd3aFA=,iv:4tOc6JcviHH1rKwhCEzRMCQeDfAQaMtmIODmqJCyevU=,tag:1Cs7wI9G21Y7V6p2o6uUeA==,type:str]
    pgp:
        - created_at: "2023-10-16T09:26:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA38T7Az157GMAQ/3dT9K0au18G2i0XSp+VrKvTGhD9LY8Ug+Vc3KsXibgiS4
            POk/kODlCIsitMLfTfEHRsSuumc3Zd34h+Etlo8Efm5XFq0t43O6opI1WrxaD0e6
            Qm6eNPLm3V7bs7flHJgiV7MV33d29LMKZR22qP+4nwOF8IbbcP8jGpMOB9fd3jYY
            OfCH61QzWJKUmm1Qvtg1Lg6vLm+Lmp8bZZHQ3rbOat2mJdjBNIO2AAZ8ya3TCN+X
            pV/BKwC/nME0UEkIhH9QZxyU+onde5xd+7oJynqRmbkNVbLirG0J9iqCQBhvVO+A
            kPQAk3/d6bvCv6XgLwS6CYCUYEkae3q1yoARG6payfOiuuRmFpjp5VFEuQQI14FB
            M7qq8fdtXQLkDFKZVC0yil35W1MV1QwCfYDh2YmfwJXRthvm1nq2JznHUuDYOAyp
            F0KoCmZDxkTMXpnpm7wcaUP1QUUd8Py1z/I1uW2FR+0dRd170RFdD1iQYwlXciBY
            fhuI+JIOXCPFHDb/qAu0eKfNBWxOq6rzaQKP4Rz/IyDk4dwR+6JRdUvMJRGPc57b
            HHzvTK6t5NrUoHbkMb9gG8Bm/v8Wk5fpo9QzSeDZcGqbqqtRIokNluVIFqgqgRV2
            krJrUm+yvuQeal6EOvVw2ARRaHSoiiyv8/KKgl96tXN09uzH+b4QI4bSLLTNqNJe
            AWyj79StJbdILcLMdltC/p2KQ+FZzY++WggnIpuQMCw8chKfPl1Hw73BR5UiSemA
            /nWlNdVwdCN5Z6VHMcB0gT4VlhYmtUGwWd80XlCgkminYQypKXWZ6VMbjJChKQ==
            =Qwbf
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapi
    name: chat-copilot-webapi
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapi
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapi
        spec:
            initContainers:
                - name: wait-for-web-searcher
                  image: busybox
                  command:
                    - /bin/sh
                    - -c
                  args:
                    - while [ $(curl -sw '%{http_code}' http://chat-copilot-web-searcher -o /dev/null) -ne 200 ]; do sleep 2; echo 'Waiting for the webserver...'; done
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapi:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapi
                  env:
                    - name: Authentication__Type
                      value: ENC[AES256_GCM,data:scl2hlgcTw==,iv:mKxrEhkdq1FeIJtr4FThXgvx4WHndlM5Cgmr1HSElrs=,tag:wMG4M1EoHzxQhJbhVAghCg==,type:str]
                    - name: SemanticMemory__Services__Qdrant__Endpoint
                      value: ENC[AES256_GCM,data:QzciUFFWOmMR8rwDBHVB5xEORxzY9ulq/A==,iv:0R059XAqkb4AN8ZKV5/r6IrfRJGblp1UZ17elZY0g54=,tag:zNAkmOb3EFj67aU/TXZakA==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Host
                      value: ENC[AES256_GCM,data:UHNjivY4i9jI1jKko5CjyjE=,iv:9+v96A9d+owMSdH1rjdX8Ll65wdOVvjGJMbtspUO+a8=,tag:OL5IHEaQ58CFpdpZZSGVgA==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Port
                      value: ENC[AES256_GCM,data:eYx1Sg==,iv:wA9LyKhrKrfL8k77P3Ga3gI3VJnprmDcngk6qXjkFR4=,tag:fvwa2jBYQ8P/mRlee/lLhw==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Username
                      value: ENC[AES256_GCM,data:fB3PwGFpjIs=,iv:naMWn3mQi4btu2wBc7rcbqhHicp7JT79wTNUz0oA7co=,tag:M5Wg3/DalDV6ygIeK6MKlw==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Password
                      value: ENC[AES256_GCM,data:WLR4/DhniH0=,iv:1LuSK7e1d1U3DcUDc9zZisy6rgqk98LjW2v88jbwQQ8=,tag:WT2MScLL2oMlQPEIqLrQvw==,type:str]
                    - name: SemanticMemory__ContentStorageType
                      value: ENC[AES256_GCM,data:SjWITuePQ+MXcPIEhixKEm4=,iv:7lpbPDqg3qVOcHNDDEE41nR5yYqkuXDyEs7Qhtz163I=,tag:NHIfMj5aOpZC53tjeparWQ==,type:str]
                    - name: SemanticMemory__ImageOcrType
                      value: ENC[AES256_GCM,data:xSUIETz6ZwtR,iv:Qd4GLQOcF2F967muv++Oidlli3TDLcqbgUFDTGxK6SI=,tag:HQdTO1EyhZmtrTLnxqc8hQ==,type:str]
                    - name: SemanticMemory__TextGeneratorType
                      value: ENC[AES256_GCM,data:cUbo+5GR1/peW5w=,iv:wAqeUQdbUdgcnGzw7Nz8uqt/V5LY6ZlfG6g3QExunVA=,tag:Wcdd+srF13veEQFocj6e3w==,type:str]
                    - name: SemanticMemory__DataIngestion__DistributedOrchestration__QueueType
                      value: ENC[AES256_GCM,data:FbqfS/NSHOk=,iv:qjnpiOlNhpnfUAEF8axPjOacX2XFIQURswd39gmJ9IA=,tag:LCcFTqmZIYUpRQxoOdkISA==,type:str]
                    - name: SemanticMemory__DataIngestion__VectorDbTypes__0
                      value: ENC[AES256_GCM,data:HN7NMlF/,iv:QGANhQ+Wu8CivevPUKGLy+vyTFHZ+f9BU0QjbdIgeag=,tag:ph6+5NsVGQbpyd+neWF9Ag==,type:str]
                    - name: SemanticMemory__DataIngestion__EmbeddingGeneratorTypes__0
                      value: ENC[AES256_GCM,data:K1NpG/ZAb8/UaZc=,iv:gpbJofukKe1Eoy09L9OReoAgnYqc64a8fQSEZCQ6CmU=,tag:+BJpzQYk7IvPT5HC36LYDQ==,type:str]
                    - name: SemanticMemory__Retrieval__EmbeddingGeneratorType
                      value: ENC[AES256_GCM,data:e1t0VUD9KVAI9gM=,iv:pDuV5wwo3+CHoYRqQ4mtcykTRal/MjM/Wb3u7V/pRCw=,tag:HfibQpiOxLv24GsO78jfxQ==,type:str]
                    - name: SemanticMemory__Retrieval__VectorDbType
                      value: ENC[AES256_GCM,data:rye5Tq7T,iv:vE8D0zUMqYBucR0rzUgD8p5hISiAu4owMvv4MzBAwzs=,tag:xOz5bEfk/au5xVCgOLdwUw==,type:str]
                    - name: Plugins__1__Name
                      value: ENC[AES256_GCM,data:TcPOgerIc9CqOKE=,iv:fZ3fw3X4BUwr3IAOpDxE7VaCg6O4yq2pR6Es+Mu9h3Y=,tag:4ScfgXe9/XlUv22lFv6MDQ==,type:str]
                    - name: Plugins__1__ManifestDomain
                      value: ENC[AES256_GCM,data:kVDQIyBwfGR227RIg1LhU1obt4bPdWcPr5CrXgztybo8NZSsnmMAFmrh0dOe16ZX5w==,iv:Ax8CjCHupSJVQlVqZBfivhybZ9guY6FM/7Dt614fLQo=,tag:zGurw0xEFeHuQ3qBpXxyYQ==,type:str]
                    - name: Plugins__1__Key
                      value: ENC[AES256_GCM,data:8g1ssvRH06UjSKw4zKrTMJtDZjs0//zZSo4zOg4Oe1kQ0b4rJOlQU0+u8t8=,iv:B3ufhza9SpM9NyTOLFJDJfjeVjLiNfOGshGhg55AOlY=,tag:Husn76vY5WAv3iHqdHdiCQ==,type:str]
                    - name: Authentication__AzureAd__ClientId
                      value: ENC[AES256_GCM,data:pMsQdj1RbSbAC6tbPFBWNhqKNogBxGAMcd9vTPlztMaButWw,iv:FpWi2QFwrN0mO7NWXHz+sEH97eNeS1viELxD/rDjivw=,tag:hK7UxjC5S9zP6nqjDtlTEg==,type:str]
                    - name: Authentication__AzureAd__TenantId
                      value: ENC[AES256_GCM,data:dsdFIrFkwInCeE0PvU9cPe11JrYfJuBHdYkdYK+906AU3jaY,iv:3eWhMIvTQN1pvmSX3E63Z/0gl3ujpcP21U7ZbtLjl9o=,tag:5SssVifjNUjNI8wwaUkv4w==,type:str]
                    - name: Frontend__AadClientId
                      value: ENC[AES256_GCM,data:IIBxwCM4DuitbDF6I8bK0IZdGMx5K/C8xpR4spnOE6kJAH6p,iv:sAfqNmaSjQ7DQDWBOckqWnJLekujUlTJbwh/H9Dg/MA=,tag:lQocp///Au2th94O4ap6/w==,type:str]
                    - name: AzureSpeech__Region
                      value: ENC[AES256_GCM,data:LrAI5JUMcuXC,iv:idyCOuBnsMIOh/swBD3Krz0hwrZPdSCyg68UmkP+c90=,tag:tE6lk9ru8ZcWHdvdb198SQ==,type:str]
                    - name: AzureSpeech__Key
                      value: ENC[AES256_GCM,data:r7PWGIsfTod1Ocy+/t8mh2vyfyVfEQVoC5yaVXWLWr0=,iv:7ISZ67ocjjTUAclk+6t1i8fZXbCnRP9aIijHPWXdDbs=,tag:gWFtG425fhE6aeN20GN0IQ==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Deployment
                      value: ENC[AES256_GCM,data:26vk12IrFlAeBKLa8kgq94HhEfGzXA==,iv:6wcm34NYN/nesAlSzyo2m3ttfndr6ByZKP8UkrbRtnc=,tag:P/52KoZxOwk074ur2dz9Vw==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Endpoint
                      value: ENC[AES256_GCM,data:FmIxvJ6CPqZQb7mRWsxIXbSSRBdO0sAKmF5JSDfS5yBAxQ==,iv:Q/lYj9n8rm1Ool2RK4/OUd65bZsvlEB3RWgRG41Uwko=,tag:8csWNvluphKj48z3N0W8MQ==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__APIKey
                      value: ENC[AES256_GCM,data:V+bjRnNBaf4imLmj8o5FjC+Ji0Rco8XGcDWI04+lAZE=,iv:UkG3pEtyMvvnd1SSR0sf9rbNMf34Qct0CRGdwuq8eGc=,tag:ZUr06H6C3dOUmZF4hV3DsA==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Deployment
                      value: ENC[AES256_GCM,data:KYlqtmnwOgSjqCa5,iv:Nb6+rVeYX2A8EkUr1f3jE2gbYLMg1nPJspost/h8Ggk=,tag:14clXarLuWGEmqdwjCQUeQ==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Endpoint
                      value: ENC[AES256_GCM,data:eYsoRflcPzMcHD9GU1N7Ms7yvXVLvy1uhcKQrs5CfNF4VA==,iv:PwJ42nFDszof62jiacWaP+i+pn7qyUP3ga1x24ig4Rg=,tag:oVZ50QeXHNGf2gzScwk4ZA==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__APIKey
                      value: ENC[AES256_GCM,data:hz04gUkSKRcK8/n34Qjmbc/QpDD6UHfm26dM2Yrxg4g=,iv:cq7qWgqqyXeRa2FFjtg2rpdWEdBlcgaWWaRQ4JWMxEk=,tag:KVq/8UItShcw5bxRQRgdBA==,type:str]
                    - name: AllowedOrigins__0
                      value: ENC[AES256_GCM,data:Cn9bWo1Tis+rVeYreWfg4JBbee673yZqdvBuIoQOa9ToIszFYZJAa8Q2,iv:kyxoPA0wxkzWRLzU3f1kpIAAKJaU/2GZddyDmkGXfqI=,tag:2PTYyu8AnSkyB3DmC8Gy+Q==,type:str]
                    - name: AllowedOrigins__1
                      value: ENC[AES256_GCM,data:F3wyRillOjWASeym23Jqm8WYKzKanUKXADlag2lQ71JaN44POGT88OC3pw==,iv:AxlLnf7lAWQCK6wQB/DYnjEejq/+vgRL/VhR5Sg9mLI=,tag:pmHKaohu751D9Ped1CAxzQ==,type:str]
                  ports:
                    - containerPort: 8080
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:26:12Z"
    mac: ENC[AES256_GCM,data:jpm09FEreziDgTuaxvPnPj0H9VhAKA9dgJP8ZF3rmAL0AlJ1x9GTpK5TaghcBvM5aKgPcoSdziWwbZb+HXNpTQROYAMmTxV5SbriQrFGTg7rR6XKu4k5TJvXxttbfRdxcIqpbv3ZJxCd6JSh31oM4EckngdIohaT1EwR5pd3aFA=,iv:4tOc6JcviHH1rKwhCEzRMCQeDfAQaMtmIODmqJCyevU=,tag:1Cs7wI9G21Y7V6p2o6uUeA==,type:str]
    pgp:
        - created_at: "2023-10-16T09:26:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA38T7Az157GMAQ/3dT9K0au18G2i0XSp+VrKvTGhD9LY8Ug+Vc3KsXibgiS4
            POk/kODlCIsitMLfTfEHRsSuumc3Zd34h+Etlo8Efm5XFq0t43O6opI1WrxaD0e6
            Qm6eNPLm3V7bs7flHJgiV7MV33d29LMKZR22qP+4nwOF8IbbcP8jGpMOB9fd3jYY
            OfCH61QzWJKUmm1Qvtg1Lg6vLm+Lmp8bZZHQ3rbOat2mJdjBNIO2AAZ8ya3TCN+X
            pV/BKwC/nME0UEkIhH9QZxyU+onde5xd+7oJynqRmbkNVbLirG0J9iqCQBhvVO+A
            kPQAk3/d6bvCv6XgLwS6CYCUYEkae3q1yoARG6payfOiuuRmFpjp5VFEuQQI14FB
            M7qq8fdtXQLkDFKZVC0yil35W1MV1QwCfYDh2YmfwJXRthvm1nq2JznHUuDYOAyp
            F0KoCmZDxkTMXpnpm7wcaUP1QUUd8Py1z/I1uW2FR+0dRd170RFdD1iQYwlXciBY
            fhuI+JIOXCPFHDb/qAu0eKfNBWxOq6rzaQKP4Rz/IyDk4dwR+6JRdUvMJRGPc57b
            HHzvTK6t5NrUoHbkMb9gG8Bm/v8Wk5fpo9QzSeDZcGqbqqtRIokNluVIFqgqgRV2
            krJrUm+yvuQeal6EOvVw2ARRaHSoiiyv8/KKgl96tXN09uzH+b4QI4bSLLTNqNJe
            AWyj79StJbdILcLMdltC/p2KQ+FZzY++WggnIpuQMCw8chKfPl1Hw73BR5UiSemA
            /nWlNdVwdCN5Z6VHMcB0gT4VlhYmtUGwWd80XlCgkminYQypKXWZ6VMbjJChKQ==
            =Qwbf
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-web-searcher
    name: chat-copilot-web-searcher
spec:
    selector:
        matchLabels:
            app: chat-copilot-web-searcher
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-web-searcher
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-web-searcher:main
                  imagePullPolicy: Always
                  name: chat-copilot-web-searcher
                  env:
                    - name: PluginConfig__BingApiKey
                      value: ENC[AES256_GCM,data:04CSoRkEkkeruFkdvHTKR/eaXjp/MzGDS3biK8xgSYI=,iv:JECRJ716AwG/XM4C3cJARpHBboMwsTby3W04WDN04Fg=,tag:0n9Jlt3etEaXC1HcQDIwLA==,type:str]
                  ports:
                    - containerPort: 80
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:26:12Z"
    mac: ENC[AES256_GCM,data:jpm09FEreziDgTuaxvPnPj0H9VhAKA9dgJP8ZF3rmAL0AlJ1x9GTpK5TaghcBvM5aKgPcoSdziWwbZb+HXNpTQROYAMmTxV5SbriQrFGTg7rR6XKu4k5TJvXxttbfRdxcIqpbv3ZJxCd6JSh31oM4EckngdIohaT1EwR5pd3aFA=,iv:4tOc6JcviHH1rKwhCEzRMCQeDfAQaMtmIODmqJCyevU=,tag:1Cs7wI9G21Y7V6p2o6uUeA==,type:str]
    pgp:
        - created_at: "2023-10-16T09:26:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA38T7Az157GMAQ/3dT9K0au18G2i0XSp+VrKvTGhD9LY8Ug+Vc3KsXibgiS4
            POk/kODlCIsitMLfTfEHRsSuumc3Zd34h+Etlo8Efm5XFq0t43O6opI1WrxaD0e6
            Qm6eNPLm3V7bs7flHJgiV7MV33d29LMKZR22qP+4nwOF8IbbcP8jGpMOB9fd3jYY
            OfCH61QzWJKUmm1Qvtg1Lg6vLm+Lmp8bZZHQ3rbOat2mJdjBNIO2AAZ8ya3TCN+X
            pV/BKwC/nME0UEkIhH9QZxyU+onde5xd+7oJynqRmbkNVbLirG0J9iqCQBhvVO+A
            kPQAk3/d6bvCv6XgLwS6CYCUYEkae3q1yoARG6payfOiuuRmFpjp5VFEuQQI14FB
            M7qq8fdtXQLkDFKZVC0yil35W1MV1QwCfYDh2YmfwJXRthvm1nq2JznHUuDYOAyp
            F0KoCmZDxkTMXpnpm7wcaUP1QUUd8Py1z/I1uW2FR+0dRd170RFdD1iQYwlXciBY
            fhuI+JIOXCPFHDb/qAu0eKfNBWxOq6rzaQKP4Rz/IyDk4dwR+6JRdUvMJRGPc57b
            HHzvTK6t5NrUoHbkMb9gG8Bm/v8Wk5fpo9QzSeDZcGqbqqtRIokNluVIFqgqgRV2
            krJrUm+yvuQeal6EOvVw2ARRaHSoiiyv8/KKgl96tXN09uzH+b4QI4bSLLTNqNJe
            AWyj79StJbdILcLMdltC/p2KQ+FZzY++WggnIpuQMCw8chKfPl1Hw73BR5UiSemA
            /nWlNdVwdCN5Z6VHMcB0gT4VlhYmtUGwWd80XlCgkminYQypKXWZ6VMbjJChKQ==
            =Qwbf
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
