apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapp
    name: chat-copilot-webapp
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapp
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapp
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapp-nginx:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapp
                  ports:
                    - containerPort: 3000
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:36:40Z"
    mac: ENC[AES256_GCM,data:gOSpnR1lGVYc/uhmiKBYEj0J+IcGP9lNSTaOCcKgD94HpcG/cQsGA+4WjRr9U95y33r+37sYlZ8TrJzyYdADMzGgHfAf33GUkyXv2mb2kUImMQAXgeL8vtuUNe7Uo8epbDJWKXpppmuwbcTISVqeivFaQoaKTdFkD4V4031hUqs=,iv:xRSOrTKMT8q9OpofHTRvauPXkhv6Yw6m8cl6c9e2+F4=,tag:2eLWwNouYap3wqlSWXLnCw==,type:str]
    pgp:
        - created_at: "2023-10-16T09:36:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMARAAjYPGfj70HnsueH3NFKIRPZcrkkvTG8yfPVndoV1wimMP
            hkG4wBVcgPf4EIQihCg6hYNdFlh1gXPSo91JrOeDV43nDXVakn2Op1Ugbrqwj0Z2
            MPMnWq9Jl1uopXoY9ezv/ydMCwOK4EdxssWJCVgPieDztpwRYOkzpmlSRc0Zy1PH
            BHdMe8cglPncuZjiaYGQp1ScqvrQiuWHRdN7duggSpR25Ngy3s0xStvZuNs2kgvN
            zIcMeXFYVgkFjWo0sI/ve4DcO9guJp99Z16NqMnDUCp8HFIDNVK1lu4J+hN4Qj5N
            0WfPKyrHgDmdQoNRoo5zORYyydLGeaFZ1ge5rrRXtJ9UE2NPnquRluAtXciOm7CM
            qBPKd1C5TW+DWuS8C7N8dbbl5ixLy1EkjMzyaoheBBtvCtzlsHqO9gZHZjOEcx9q
            gnKAs62e/1anld0iDbbGc6YPujo1yeiqaHkpEydZu0nxrkNsLEZO/1XSiazbWBLM
            cR3c6DAwVH6GEMeI9scYCm11B5k5AAY9gjeHSF/3N4aikp8H6hWgwKOABpqpWzDC
            uuM9j6EtqgMDLpK7PwVS1FHpBFjJejP6kXlTBY0WBE/4imizf90yMSZ8kfchZnby
            Rk+wlW8rrkXKvymCNO61hGElwSEpRuy8XpsQJ/s5D0LIlEL9+rPbzd6RPhGyqPzS
            XgEz8CIvPsW0Z6loOQhGaKXYIjtGLcj2mCsrz64w2c7DC08rdHQwNVVEY0pkPhJp
            MrCLwwyPa2K76qtn/CL096z+MC7T0MXFMCwPHGIw3GMqsDBMRkpA7EUIOOtiGyo=
            =Ypdw
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-webapi
    name: chat-copilot-webapi
spec:
    selector:
        matchLabels:
            app: chat-copilot-webapi
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-webapi
        spec:
            initContainers:
                - name: wait-for-web-searcher
                  image: curlimages/curl:latest
                  command:
                    - /bin/sh
                    - -c
                  args:
                    - while [ $(curl -sw '%{http_code}' http://chat-copilot-web-searcher -o /dev/null) -ne 200 ]; do sleep 2; echo 'Waiting for the webserver...'; done
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-webapi:main
                  imagePullPolicy: Always
                  name: chat-copilot-webapi
                  env:
                    - name: Authentication__Type
                      value: ENC[AES256_GCM,data:jCDdaKMqaw==,iv:DVdYYeJYo726K7nf+Ej3rGxNGWZ0ZFOjq6mOLLLV3Ls=,tag:v3ApcC6TyvsyzFP238RvTA==,type:str]
                    - name: SemanticMemory__Services__Qdrant__Endpoint
                      value: ENC[AES256_GCM,data:V3kJTlwkB8dYuzCSfvG8sUxCVC7X65CS5g==,iv:BjNOsy05Xv7sBl+1cTJD4k1usPkX1GMYPEt96MwJcaM=,tag:V6dYDuMLrQqB5FSAtGpwdg==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Host
                      value: ENC[AES256_GCM,data:Us1UJpbTD+VapVg8AHcNDyQ=,iv:kBRCW32tECM/5Xs6L49VqchJb/n3o70RAYcRwVtNEuQ=,tag:RA7cWXh1I4xMtxajRLSCvA==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Port
                      value: ENC[AES256_GCM,data:4C+SvQ==,iv:CWUqlMuw6CLUgCljwp4/awecBBU/OEZZWq8yybUY8nw=,tag:7Y7blrw3RP3ilE3B7jVMJw==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Username
                      value: ENC[AES256_GCM,data:J1i3d+fHXyY=,iv:lBluaUJpLHlD0f0bSigLAW6rI1vtO1xFd5sk9fRcUWo=,tag:JnUcS/B4/lBPTSD9/zveSA==,type:str]
                    - name: SemanticMemory__Services__RabbitMq__Password
                      value: ENC[AES256_GCM,data:pJ11pM99+x8=,iv:lCZhQ6l+rslcLReWNPGEq7yr5xQR4UNV4k/ZwD6WkSo=,tag:/SGUpKwbHhHJQfMcWfn7Vg==,type:str]
                    - name: SemanticMemory__ContentStorageType
                      value: ENC[AES256_GCM,data:MUASpYdYty0dHZKTHNFChLk=,iv:OU7Nacr1jURJOxRWgRnOrDqC5bIJo7O+EIvuLQf7aus=,tag:nMqN7wHzeZLmeacuJktL9A==,type:str]
                    - name: SemanticMemory__ImageOcrType
                      value: ENC[AES256_GCM,data:yiewFcBoSh8q,iv:TKiDqFq3Nyh4sZsBwiWajo69bm5XxLgM4047Eo3/IC8=,tag:w69pkkOl+jV1YFvC1NG4kA==,type:str]
                    - name: SemanticMemory__TextGeneratorType
                      value: ENC[AES256_GCM,data:RPjOYjAaJtOZ86g=,iv:Xjvc3DDIzVaAalBX5Xa7GqE3WZ22lAwT0bf79cLZKC0=,tag:CJP3SqsOtrgBgF1WFh4vSg==,type:str]
                    - name: SemanticMemory__DataIngestion__DistributedOrchestration__QueueType
                      value: ENC[AES256_GCM,data:1zLkbbv1mB8=,iv:0vFVpKdrk4sprGDxAFxQD4Gs76HmOO+Gij/LpYHfULo=,tag:pRaZbEWW/TgslKSUg6PC2Q==,type:str]
                    - name: SemanticMemory__DataIngestion__VectorDbTypes__0
                      value: ENC[AES256_GCM,data:WHSDmOtV,iv:3SbZ+d/g+MlSh0rb7pj724O+fPxB8rx9bYmNSEUCJ2o=,tag:Ddk301j0WqmtPbRy7mHVIw==,type:str]
                    - name: SemanticMemory__DataIngestion__EmbeddingGeneratorTypes__0
                      value: ENC[AES256_GCM,data:MIZ+piBfCI9SHXc=,iv:Ln771ow6FRwvY1/5HWhwoDO0EbTz3Ns00gidOKqVnho=,tag:bsRt9mRVeIN3y0b+KajE2A==,type:str]
                    - name: SemanticMemory__Retrieval__EmbeddingGeneratorType
                      value: ENC[AES256_GCM,data:bfQc5k8muNqmKCU=,iv:6rx8h0YrroOd4CelEAX910GtEP7Iic26H9OlPeTYsXU=,tag:CjfWkYuAZb7RS9b9DMEVdQ==,type:str]
                    - name: SemanticMemory__Retrieval__VectorDbType
                      value: ENC[AES256_GCM,data:QCtZA4My,iv:ImQ2ouVp+MSnttpsrOt3ItbMsBpBoxH5BRfqnAKLrNw=,tag:SD96ZKPcHAUCKOxNDnRvng==,type:str]
                    - name: Plugins__1__Name
                      value: ENC[AES256_GCM,data:ORwQyOY0N+0MSOs=,iv:T7hpHn5+62VDkl/FXMLYJxVXxzRzX6f4EfxLQ+AOW/0=,tag:BYpRr4orQ5jjEam/Grzj7g==,type:str]
                    - name: Plugins__1__ManifestDomain
                      value: ENC[AES256_GCM,data:+JTW7UKcfqKq8TrosJJCavAFbIEXsBMpfShuy1sBbSpj42sOk6vIQAgkznLK5QGz8w==,iv:TjNGuSq2PMVRBQ8wA8m5ngcerXuj30ueDIJgD5BEW7c=,tag:nXIS7P4ZmWRZ1AnVuDZmQw==,type:str]
                    - name: Plugins__1__Key
                      value: ENC[AES256_GCM,data:5RHBt9OA7OzdRg5uggEUX9X75Mq0mEjn0cU5Pr7ygLCc199qWjfcxZsi1/o=,iv:CqjJ9uRQUQmDxpQq7gddF2TWFemi4gqlSO1CqbrmjEw=,tag:p2hyspTVOt7zIXZlyHUY6w==,type:str]
                    - name: Authentication__AzureAd__ClientId
                      value: ENC[AES256_GCM,data:SwZKnKVxtPcFx8nN7XCFI2dNV9tmp8zkiG/7+aaakMlelBXw,iv:8gaV8Ky+LXSFwdgG3I/bIb1kBR3kAQS0QvF2H/g8iLw=,tag:k8qzDjFl1p+OZJmRetnNlw==,type:str]
                    - name: Authentication__AzureAd__TenantId
                      value: ENC[AES256_GCM,data:KhHa+sWPZExbnaxGsq8N1JaPSmgD6m24FpC8InnKop3a3Xdh,iv:TAyDI8uqblEqcMDbnf34MVpzlos5ZMhedfq3GWq1mVQ=,tag:dbAWFvMRMKbsjekS4oxBkQ==,type:str]
                    - name: Frontend__AadClientId
                      value: ENC[AES256_GCM,data:rUMG4yOLEOAPNCwcjgXJkzJ3al7R7lLw8lNMmAmUQQ/Xzxkj,iv:yHVxaHrROp64F31cKfmtEJPeyLjcbaVfdcX2FuJ8S04=,tag:tgMxWAnHMmpXzAtv/w0www==,type:str]
                    - name: AzureSpeech__Region
                      value: ENC[AES256_GCM,data:e9tH29420Ut0,iv:njDskIXcijd303pSAlayQjMob5bOgv8ZnBqCwLwSJA8=,tag:Q9HwTgfzLIBszzNAaYvzng==,type:str]
                    - name: AzureSpeech__Key
                      value: ENC[AES256_GCM,data:5Drzkhv9Nn2l6uv4dqyohLms3kJcLxUem0MmqrW0Grs=,iv:yxmFfDbgtg8Zp5Io3aE5+K/yL8HQfsG/0195/EsFWM8=,tag:l6K+MbuB/GNNIVFZoQjz/A==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Deployment
                      value: ENC[AES256_GCM,data:SizkUbdT2DgNsL85M2b7m9kwJfEhmA==,iv:WYwDnCHfBRAjNU27ZJ2WiVlDu9Tc8tAQzbGkCCY7X/g=,tag:KaF2X+ogorx8VyAXWEQZdA==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__Endpoint
                      value: ENC[AES256_GCM,data:bdRwYrrU5vmDxNZdIoXM/O6Ci42Tk+ZsTkNbsupWT5gaNw==,iv:iT5nakhzy6AKFicquGdO+k+HUAMsKmlz9WMVPUJ+soQ=,tag:80mXHFwGSSAUv1EWAtjkzw==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIEmbedding__APIKey
                      value: ENC[AES256_GCM,data:I1blUJUQURYp8YNJx9PQlg1AdcpLRGGS2gdlvaGcSSA=,iv:l0juR3rJJg4Al6PizT4JKpOqcxx9cQVc5/Pt6T1P20w=,tag:5XXdXzY+QExxmmN4tpA+wQ==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Deployment
                      value: ENC[AES256_GCM,data:nAWwz9fIBcuxP94J,iv:ZtkNwE9JxlY9ltqcfdXiPxnbRTcA490rZOL8OFXzOTM=,tag:Gm8IHM64Hu7mgSPpQzppGA==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__Endpoint
                      value: ENC[AES256_GCM,data:V5zJg04i4+mCR3ww9xmXYJo2UPyxUvbmAJQ45xpsfNC/kg==,iv:wh1TbK/GpxUQAp9D/z0H5V/C5lM20LhzIFWebBDQXbs=,tag:u9jpBAL5DLVVL98Y3ih2mg==,type:str]
                    - name: SemanticMemory__Services__AzureOpenAIText__APIKey
                      value: ENC[AES256_GCM,data:4RtA+o+CzNWDfq2K521gW0rUjzLh2pY+T/VuM+LJD4w=,iv:AdsLAjutLWhOzhdhKC+SNe5QzSOjDzIr3scOzbimpUg=,tag:uU9zqC8K/m5HuLqJD/cOUw==,type:str]
                    - name: AllowedOrigins__0
                      value: ENC[AES256_GCM,data:PmaGOgIdB4l9QethdvFjMFDOhk6FKcISwcCT/RXgHmalN4E4m0cX/J89,iv:nXBdP/Fujuv1+qga+hZvaLcnh6yA3FbVDVkPg0xtK7Q=,tag:844yTKSHRj6sWkr+ewYS4g==,type:str]
                    - name: AllowedOrigins__1
                      value: ENC[AES256_GCM,data:yFeQKjVsONoG65Y+Gjvhu4e5qv7nH2U9MzXd6WBDP6SsgUZHZZMRlK0vIg==,iv:5DcCaJhmBSkZMFseogaR/Mf/b1BAY5395tattjz9KDQ=,tag:WFyXfQzJKjQb84rmiBeA7w==,type:str]
                  ports:
                    - containerPort: 8080
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:36:40Z"
    mac: ENC[AES256_GCM,data:gOSpnR1lGVYc/uhmiKBYEj0J+IcGP9lNSTaOCcKgD94HpcG/cQsGA+4WjRr9U95y33r+37sYlZ8TrJzyYdADMzGgHfAf33GUkyXv2mb2kUImMQAXgeL8vtuUNe7Uo8epbDJWKXpppmuwbcTISVqeivFaQoaKTdFkD4V4031hUqs=,iv:xRSOrTKMT8q9OpofHTRvauPXkhv6Yw6m8cl6c9e2+F4=,tag:2eLWwNouYap3wqlSWXLnCw==,type:str]
    pgp:
        - created_at: "2023-10-16T09:36:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMARAAjYPGfj70HnsueH3NFKIRPZcrkkvTG8yfPVndoV1wimMP
            hkG4wBVcgPf4EIQihCg6hYNdFlh1gXPSo91JrOeDV43nDXVakn2Op1Ugbrqwj0Z2
            MPMnWq9Jl1uopXoY9ezv/ydMCwOK4EdxssWJCVgPieDztpwRYOkzpmlSRc0Zy1PH
            BHdMe8cglPncuZjiaYGQp1ScqvrQiuWHRdN7duggSpR25Ngy3s0xStvZuNs2kgvN
            zIcMeXFYVgkFjWo0sI/ve4DcO9guJp99Z16NqMnDUCp8HFIDNVK1lu4J+hN4Qj5N
            0WfPKyrHgDmdQoNRoo5zORYyydLGeaFZ1ge5rrRXtJ9UE2NPnquRluAtXciOm7CM
            qBPKd1C5TW+DWuS8C7N8dbbl5ixLy1EkjMzyaoheBBtvCtzlsHqO9gZHZjOEcx9q
            gnKAs62e/1anld0iDbbGc6YPujo1yeiqaHkpEydZu0nxrkNsLEZO/1XSiazbWBLM
            cR3c6DAwVH6GEMeI9scYCm11B5k5AAY9gjeHSF/3N4aikp8H6hWgwKOABpqpWzDC
            uuM9j6EtqgMDLpK7PwVS1FHpBFjJejP6kXlTBY0WBE/4imizf90yMSZ8kfchZnby
            Rk+wlW8rrkXKvymCNO61hGElwSEpRuy8XpsQJ/s5D0LIlEL9+rPbzd6RPhGyqPzS
            XgEz8CIvPsW0Z6loOQhGaKXYIjtGLcj2mCsrz64w2c7DC08rdHQwNVVEY0pkPhJp
            MrCLwwyPa2K76qtn/CL096z+MC7T0MXFMCwPHGIw3GMqsDBMRkpA7EUIOOtiGyo=
            =Ypdw
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: chat-copilot-web-searcher
    name: chat-copilot-web-searcher
spec:
    selector:
        matchLabels:
            app: chat-copilot-web-searcher
    replicas: 1
    template:
        metadata:
            labels:
                app: chat-copilot-web-searcher
        spec:
            containers:
                - image: ghcr.io/huangyingting/chat-copilot-web-searcher:main
                  imagePullPolicy: Always
                  name: chat-copilot-web-searcher
                  env:
                    - name: PluginConfig__BingApiKey
                      value: ENC[AES256_GCM,data:LXJYFBIfoMp0HnGIlvyAtmbPTd7m0B2uqqSY9FMqvbo=,iv:N3MWlPQEj8l5oZBbmPh8Om4P6aTzQSZMHyPubYKzRMs=,tag:mMVyHNl4xEcmH3AOrLp2IA==,type:str]
                  ports:
                    - containerPort: 80
                      name: http
                      protocol: TCP
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-16T09:36:40Z"
    mac: ENC[AES256_GCM,data:gOSpnR1lGVYc/uhmiKBYEj0J+IcGP9lNSTaOCcKgD94HpcG/cQsGA+4WjRr9U95y33r+37sYlZ8TrJzyYdADMzGgHfAf33GUkyXv2mb2kUImMQAXgeL8vtuUNe7Uo8epbDJWKXpppmuwbcTISVqeivFaQoaKTdFkD4V4031hUqs=,iv:xRSOrTKMT8q9OpofHTRvauPXkhv6Yw6m8cl6c9e2+F4=,tag:2eLWwNouYap3wqlSWXLnCw==,type:str]
    pgp:
        - created_at: "2023-10-16T09:36:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMARAAjYPGfj70HnsueH3NFKIRPZcrkkvTG8yfPVndoV1wimMP
            hkG4wBVcgPf4EIQihCg6hYNdFlh1gXPSo91JrOeDV43nDXVakn2Op1Ugbrqwj0Z2
            MPMnWq9Jl1uopXoY9ezv/ydMCwOK4EdxssWJCVgPieDztpwRYOkzpmlSRc0Zy1PH
            BHdMe8cglPncuZjiaYGQp1ScqvrQiuWHRdN7duggSpR25Ngy3s0xStvZuNs2kgvN
            zIcMeXFYVgkFjWo0sI/ve4DcO9guJp99Z16NqMnDUCp8HFIDNVK1lu4J+hN4Qj5N
            0WfPKyrHgDmdQoNRoo5zORYyydLGeaFZ1ge5rrRXtJ9UE2NPnquRluAtXciOm7CM
            qBPKd1C5TW+DWuS8C7N8dbbl5ixLy1EkjMzyaoheBBtvCtzlsHqO9gZHZjOEcx9q
            gnKAs62e/1anld0iDbbGc6YPujo1yeiqaHkpEydZu0nxrkNsLEZO/1XSiazbWBLM
            cR3c6DAwVH6GEMeI9scYCm11B5k5AAY9gjeHSF/3N4aikp8H6hWgwKOABpqpWzDC
            uuM9j6EtqgMDLpK7PwVS1FHpBFjJejP6kXlTBY0WBE/4imizf90yMSZ8kfchZnby
            Rk+wlW8rrkXKvymCNO61hGElwSEpRuy8XpsQJ/s5D0LIlEL9+rPbzd6RPhGyqPzS
            XgEz8CIvPsW0Z6loOQhGaKXYIjtGLcj2mCsrz64w2c7DC08rdHQwNVVEY0pkPhJp
            MrCLwwyPa2K76qtn/CL096z+MC7T0MXFMCwPHGIw3GMqsDBMRkpA7EUIOOtiGyo=
            =Ypdw
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
