apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    name: chat-copilot-webapp
spec:
    ingressClassName: nginx
    rules:
        - host: ENC[AES256_GCM,data:KqtcnJSHWldZOKeyf4W7zkzM0C3uXoG0d5yQPzLA503+WEk=,iv:6kfasBGRxW+RiXbiya69dvrR6zcBB944eagTpS5Q4Uw=,tag:DIpQW7lLO+63d5pM0aJCug==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: chat-copilot-webapp
                        port:
                            number: 3000
                  path: /
                  pathType: ImplementationSpecific
    tls:
        - hosts:
            - ENC[AES256_GCM,data:8Z+qUn9WtBkqKL618Q2x9ct4UVVgghI4lGC3w3ZAHE4wwDw=,iv:CpCvha7/NpAYrGoxI0domGv35mPMAu4gSxZwjgBTUGk=,tag:AJPkBQZKdAJiPVwEtN14Mg==,type:str]
          secretName: chat-copilot-webapp-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T03:19:35Z"
    mac: ENC[AES256_GCM,data:PiBYsrbl4yKYsxgfG9VYjoFVXHGp5WeN51wyw9A6Bxc4QnECvzmANtBXTLa2r3y1dhwy4A9pa/4baHaPeR070zuQfTcFAyuhQEZ9w3kqRAs8RDyo72uR7R6mIF0YrRSMJqc8rUYaiMOc/q49LNd56/GbcQuWJZh2EuBqcwDyiAM=,iv:q+hiWSnQlyNbMebn+/zW8js2vdPevUqEpqu8m/QFz58=,tag:/C9KJEHZoovs/4E1G3rMuw==,type:str]
    pgp:
        - created_at: "2023-08-17T03:19:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ/5AcSEF1CNxiJLZCh2gnLflALTXmdzKr/V7TQ8mBRcFRkv
            v77W/7ZpL03WJRbKNjsdjYfNW7AuLNnmrENfL+XsIlqITu3bvfemW1xzO/WcSfm4
            Do0u6hb6eCSU5T4yfF4SGWDJzLpOwFF+oJbv9VkSNTYs3QuwKlDJ5tqCk0xUuxxE
            ++crVsPwx7x0EuOVLJiunWs/LqSBc645bk3WooqbQCDBjLu66ISJ3ZFG2IPHnBt+
            SUb2Zs1DDZJOIYN7bCeiStKVate/KbYw/ToUMkqI6TVIW2Lt38+cGtWb+E03EyKv
            tJIB2hJcHdT3xHfk0DXFRo8YP9GL1f4j3hEEjvcSzFU3ctaIYcISNAqW6N5nL3Qh
            jlgiXKV9PNIFr8NeW2FuvqTy3+aOhzYuvoIUTs+uRtca/TYcctVJuB/Y884sc5DC
            6MXPX1W3fLjNhBodO9IGt5l95NrMB8p6obnLPswITH2cMoyywlu8h+jUXqqehikf
            qF+E+nLjrjT3nCF24PmelO4vVroB/h75ML4/AkNagVmGsjUfLHF+hwLGgtaCOCPw
            Njf0KSQZy33o4q4MAStNNzvb12VTfD1pwik1f/Esv8qsTFY8H573PqIXcItQuaaJ
            oRzLTQC3OUfkR2iRuSckUZTAHuGAsSOpInEFUM++3dnaJ11TpMlvHMaVXa1o5MzS
            XgHRKRHcNzfUlGodMk31/+mn8IidTpWWzIeCNBLaJZ32rsxlcEuiBCS9J6Q5vkJk
            I0hkSwbvr5Gvv0CEPZ+KLBZFBCeK2Y2hg1hpbastZ5sBm0KmKK3FU91W7eIBu38=
            =n3hB
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    name: chat-copilot-webapi
spec:
    ingressClassName: nginx
    rules:
        - host: ENC[AES256_GCM,data:HmdtNDUSpY8vCaFGS+OYkzPEsWs7mDv/Pb4W1V4ROujYV00=,iv:ITjYlcstVmG9/262f3wU8ydJF3GBtTJUgFqlS5B+27M=,tag:pR9PSCwb1AIoWPn+ReixHw==,type:str]
          http:
            paths:
                - backend:
                    service:
                        name: chat-copilot-webapi
                        port:
                            number: 8080
                  path: /
                  pathType: ImplementationSpecific
    tls:
        - hosts:
            - ENC[AES256_GCM,data:L5YGhoa0VAgCcAf37e7U1inE15dxWHzjJCzIw0vCiV6YPUY=,iv:NZKbwd7qJS7bdXz7j6MKc+VGvYRdpaxD1LVsBgMsXS4=,tag:D4r/dHeFljJMv9KW6x1k3w==,type:str]
          secretName: chat-copilot-webapi-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T03:19:35Z"
    mac: ENC[AES256_GCM,data:PiBYsrbl4yKYsxgfG9VYjoFVXHGp5WeN51wyw9A6Bxc4QnECvzmANtBXTLa2r3y1dhwy4A9pa/4baHaPeR070zuQfTcFAyuhQEZ9w3kqRAs8RDyo72uR7R6mIF0YrRSMJqc8rUYaiMOc/q49LNd56/GbcQuWJZh2EuBqcwDyiAM=,iv:q+hiWSnQlyNbMebn+/zW8js2vdPevUqEpqu8m/QFz58=,tag:/C9KJEHZoovs/4E1G3rMuw==,type:str]
    pgp:
        - created_at: "2023-08-17T03:19:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ/5AcSEF1CNxiJLZCh2gnLflALTXmdzKr/V7TQ8mBRcFRkv
            v77W/7ZpL03WJRbKNjsdjYfNW7AuLNnmrENfL+XsIlqITu3bvfemW1xzO/WcSfm4
            Do0u6hb6eCSU5T4yfF4SGWDJzLpOwFF+oJbv9VkSNTYs3QuwKlDJ5tqCk0xUuxxE
            ++crVsPwx7x0EuOVLJiunWs/LqSBc645bk3WooqbQCDBjLu66ISJ3ZFG2IPHnBt+
            SUb2Zs1DDZJOIYN7bCeiStKVate/KbYw/ToUMkqI6TVIW2Lt38+cGtWb+E03EyKv
            tJIB2hJcHdT3xHfk0DXFRo8YP9GL1f4j3hEEjvcSzFU3ctaIYcISNAqW6N5nL3Qh
            jlgiXKV9PNIFr8NeW2FuvqTy3+aOhzYuvoIUTs+uRtca/TYcctVJuB/Y884sc5DC
            6MXPX1W3fLjNhBodO9IGt5l95NrMB8p6obnLPswITH2cMoyywlu8h+jUXqqehikf
            qF+E+nLjrjT3nCF24PmelO4vVroB/h75ML4/AkNagVmGsjUfLHF+hwLGgtaCOCPw
            Njf0KSQZy33o4q4MAStNNzvb12VTfD1pwik1f/Esv8qsTFY8H573PqIXcItQuaaJ
            oRzLTQC3OUfkR2iRuSckUZTAHuGAsSOpInEFUM++3dnaJ11TpMlvHMaVXa1o5MzS
            XgHRKRHcNzfUlGodMk31/+mn8IidTpWWzIeCNBLaJZ32rsxlcEuiBCS9J6Q5vkJk
            I0hkSwbvr5Gvv0CEPZ+KLBZFBCeK2Y2hg1hpbastZ5sBm0KmKK3FU91W7eIBu38=
            =n3hB
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value|host|hosts)$
    version: 3.7.3
