apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat-copilot
resources:
  - ../../base/chat-copilot
patchesStrategicMerge:
  - deployment.enc.yaml
  - ingress.enc.yaml
replicas:
- name: chat-copilot-webapp
  count: 0
- name: chat-copilot-webapi
  count: 0
- name: chat-copilot-web-searcher
  count: 0
- name: chat-copilot-memorypipeline
  count: 0  