apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra  
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./system/production
  prune: true

