apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaos-mesh
resources:
  - ../../base/chaos-mesh
secretGenerator:
  - name: chaos-mesh-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
