apiVersion: v1
kind: Service
metadata:
  name: make-line-service
  labels:
    name: make-line-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: 80
  selector:
    app: make-line-service
---
apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  labels:
    name: accounting-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    targetPort: 80
  selector:
    app: accounting-service  
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 80
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    name: ui
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ui 