apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dapr-calculator
resources:
  - ../../base/dapr-calculator
  - secret.enc.yaml
replicas:
- name: calculator-front-end
  count: 0
- name: addapp
  count: 0
- name: subtractapp
  count: 0
- name: multiplyapp
  count: 0
- name: divideapp
  count: 0