apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda
resources:
  - release.yaml
secretGenerator:
  - name: keda-http-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

