apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-http
spec:
  releaseName: keda-http
  dependsOn:
    - name: keda
      namespace: keda
  chart:
    spec:
      chart: keda-add-ons-http
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: keda-http-values      