creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(host|hosts|nginx\.ingress\.kubernetes\.io\/auth-url|nginx\.ingress\.kubernetes\.io\/auth-signin|storage_account_name|storage_account_key|container_name)$
    pgp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
