apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-viz
resources:
  - ../../base/linkerd-viz
  - ingress.enc.yaml
secretGenerator:
  - name: linkerd-viz-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
