apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo
bases:
  - ../../base/echo
nameSuffix: -canary
transformers:
- labels.yaml
patchesStrategicMerge:
  - ingress.enc.yaml
  - delete-ns.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: echo-canary
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: canary
