apiVersion: apps/v1
kind: Deployment
metadata:
    name: azure-openai-proxy
    labels:
        name: azure-openai-proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-openai-proxy
    template:
        metadata:
            labels:
                app: azure-openai-proxy
        spec:
            containers:
                - image: stulzq/azure-openai-proxy
                  imagePullPolicy: IfNotPresent
                  name: azure-openai-proxy
                  env:
                    - name: AZURE_OPENAI_ENDPOINT
                      value: ENC[AES256_GCM,data:NVwk5ByLzVoexn5QyXjWnc8bqSbtmSE4o2ntNcEAefMu,iv:NXh4O/XquWQV7S4vghGCkkALdh/q+Kq2LiLnRt6y4Vg=,tag:WHAwN6Yr6Xhoo/g+xtOUmw==,type:str]
                    - name: AZURE_OPENAI_MODEL_MAPPER
                      value: ENC[AES256_GCM,data:XIhXa0uOx42Tkyv8cU/E4k++SI2ECQzhE2HTQS2YMonCdEMM7WYXDkdi54AA0cvHyhag659sxWBGlp6D0ybdzKIo0tIs1hmLr6I67fwA/nHbdLGa5b6oXSt9Bau5YoWelbRPftSTKT8nljo=,iv:IrdBlYrKMhUFCiBlWrdTjW4BtSHFQPr6mhByMs8/hN0=,tag:RNxjE/+tnr7GEbBonclS4Q==,type:str]
                    - name: AZURE_OPENAI_API_VER
                      value: ENC[AES256_GCM,data:qoRx4RZ/tgNF2A==,iv:/KGyvRY73WWaWmMQh9lavD7qANkEhTZYukuayICIG6M=,tag:ikExNAztwyO6QirJ+5DAIQ==,type:str]
                  resources:
                    requests:
                        cpu: 50m
                        memory: 64Mi
                    limits:
                        cpu: 100m
                        memory: 128Mi
                  ports:
                    - containerPort: 8080
            restartPolicy: Always
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-15T06:42:04Z"
    mac: ENC[AES256_GCM,data:xd7iIXrQ0fA9J1qfeYU+ubQ/pVcnXblin8v9CAYPUz85ZAyuehr3xnTES3RSpTZCGm+AspD0WjWdYsxO/PiJYFwwEUNXOPaw1CIwp30LZULACTv9+eQtFDY78Yarl09mZotJVX7elyemExmjtyIlz5TFT5E9g2E2tdhnaqLeB3s=,iv:IfXmLcK2fXYKA1HPpWguBujGDjJXTsbvui8wDwqmycQ=,tag:BmyGUo8/kG5FTJdvcqD3nA==,type:str]
    pgp:
        - created_at: "2023-08-15T06:42:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ/+Kc3reuDKyT5ZGWwYZaA+KeMPgHXIdsSYSJGbfPrbwNmb
            RTtB986hPGCM/55m6ms1bHGIAnn3mAd5lN1mNgIQBTAdndbKo3XqSrUeUU0c04BK
            K8+6ssocq2ykwpOXUe4gG6J7QkBpY8fkbeIJ01VRwqsJuGv/WnCIQNjjNYOLlie5
            qvOZyovLxnDjH5WYhcSfvZ5rP8cNBXHqGLBEcufMGemKebS9hZoC7DsTyXq1sQgH
            VlFZwGRAUgMnRtfX+4P2O5a3pJbrzDNCIo2/mlMemhp6e2c9iGSrxCRy8MDlotc5
            0o/osGJ1nU5/E5VhZz1U58YR/k4l9qtp0U0VWlzi+DdheQdY4gonb2toNwJyT4hv
            cPYE4roUXi3Y61dK7WGBT9xGBASe7bS4tHqqQ7Rtj1wjUofpzfsp+ydaWBq3fpAf
            foCV26TtFCI5hFVCCodWgyvxic6ljc0MV9K4osUETq5M0S0txC3wED88kWoMWkwz
            i3g5/3QHsHEswPAYRVYUahi7dRA5QrrIpPgkiJEgNq57TTCBOCpfnvyvZYUT8ZoS
            qMH0ZpRDYiu1f/wF0zc0WEvX0T7pC+zNA6Fbk4Vw5IeHEw+ci1fuKbiGtV4BB8MI
            8mDcHTHGQRmkpOGr+yZFX5DwaEoOemsVm412p+I5uWD7H6WbneH4PlV4re5PPd3S
            XAHSzJ5sPd29vwTLWZZHfBq39MrJxglKoaLyCd3eRUwUT0+06DMErpPAZPQK0eJ3
            tzhniIP99HiF9ixO8pxhO49ZNzeae64bVvU3iVwQJUSLgf2Nwy1Eehat+bnt
            =D5HJ
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(value)$
    version: 3.7.3
