apiVersion: apps/v1
kind: Deployment
metadata:
    name: azure-openai-proxy
    labels:
        name: azure-openai-proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-openai-proxy
    template:
        metadata:
            labels:
                app: azure-openai-proxy
        spec:
            containers:
                - image: stulzq/azure-openai-proxy
                  imagePullPolicy: IfNotPresent
                  name: azure-openai-proxy
                  env:
                    - name: ENC[AES256_GCM,data:ObpP/fNlTMdpRnLbem1glsPLLZ/Q,iv:/ZB+NiI1BE9xFCOFfofl7Ty5CKJ2ZFLzQ1CAsLLfPTg=,tag:CBdbawSZQFRJN44JKSKvVQ==,type:str]
                      value: ENC[AES256_GCM,data:OZDvbqGuk/rWcAobtfcbWLWz6Hni86ZEde9T46hr9c7J,iv:XSt6ZYCJUaCgbVvvEe7uvnUL1llEKnSJipfz6RVMSvw=,tag:3OA76NqYNfLeMSHO7BhE2g==,type:str]
                    - name: ENC[AES256_GCM,data:IDW/6hFVJ53kkzkX68wnQTYuM1sdgaP51w==,iv:2tH4WcuLA13Sh2mrusy3tAQSzVEnDOPBBS4Ukm5IYuI=,tag:6P7HakszKxBzN66DE+QB8w==,type:str]
                      value: ENC[AES256_GCM,data:gxKRMS26Xmuci9HcYEeHAhQevJ7HMi5Ak0ntTVv2ymx4lUJv4YsUZPqPLVfXci0vqTvlK53ObBBnIhROhYTPMGfnwCy6tcHy1+9GFv+0XV6fSUoX6m3QTElGg9CkBUqNP6KcwaSPyw4cNYo=,iv:zR3WDvDx967yvKBgGmuS2yVFUnIgbTWO9j8PMVyg4zE=,tag:WbvNJ4yH5BfVkmQUk9jehQ==,type:str]
                    - name: ENC[AES256_GCM,data:nzHjfhNtoRTcILpe1PZwPN3ljA8=,iv:idGn0UQ9CzvhTgr6uZ9OQ4bZaelIMhMJ7wrgUToEah8=,tag:i+5u1Rpp3ccKhuFTuQFZJg==,type:str]
                      value: ENC[AES256_GCM,data:zsRw9ffGxwfK8g==,iv:4vcXi77n97ixhmhXjTiy4E+2h1sjYhG1FzfqSmnXGrU=,tag:zPl1iCDepK7h7m5WLfjVsA==,type:str]
                  resources:
                    requests:
                        cpu: 50m
                        memory: 64Mi
                    limits:
                        cpu: 100m
                        memory: 128Mi
                  ports:
                    - containerPort: 8080
            restartPolicy: Always
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-15T06:38:47Z"
    mac: ENC[AES256_GCM,data:mH1+lSJmmg95OuxY/HOQqsrSqEiou0a9avNbxPWj9XdhwhDPuuiGEo8tM8io5h21fdkit7+5DVgscAIMsJj6YyANqvBuoPdG5lr3gDfI6r0rsuyq5Wy78plSwJDVMMa6xKP4OyEgXl3fxCbA+9ws1RE7h5E77ipnys09RPFbWv8=,iv:P82bGdJqGLsu1PYGoUG8j2D205RPjSBkzAcsaLTDakI=,tag:yQ/c7o2ZXZ29l2+A5YWriQ==,type:str]
    pgp:
        - created_at: "2023-08-15T06:38:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMAQ//Z0iYvZqSnijniYcDw99RqHJSOgRjvTH/nOVmmcBXN1tK
            t9R+3WMLs8k6v06kCliBUdZqj8nogVn4u/bt0bNz6JGOMOKxfOW2NgOZ3WI8aIrB
            Ie4D0fzE2j+2S5hJ1z6fegwroH6j20MLVFAs38iIaWxfMhjWjItX6SJQOnBoKwcO
            jGns1OGD/Z55+EMwrBScUWtVwnJshzNN3N+3vJXSVEBZE54DlOyn5dT/NwpO8m5r
            1Z5efm3T8ijyQy2YtaXhwHHBI7vMZFiJ7PSbCCpIGeiPMHnWfbRDdIEojCwLYzsi
            AaZTmiiLdCYncmc+p/oq8QeXWqYDLC8W605rafrEVUqyzzJUIzLb4Smy/kHLtH0Y
            e8cXKt1cJb4LUucZdebUav8hWzDSAaDiD0PV4SW3SY9x+jwT92MahruuCwL9ZIfM
            sw7mxhmn6WPcjRVTUbXbCcc9EGAVXWdcLmzl60CiE/YbmoXBkWDT84RVWF3hFUJb
            9urA2zhp32jBk0yiGF4ukwCQ0z8t9us/C1Rlzx98zO3E7cJvq6GWGgO+KpwQImxI
            kvMfoQFisW40ssMSbISjlFHsLGDMscaP0OMp6YIXWZPz9VfbrNKQnXDDrhaAxAhm
            c01ztiGDINlsESTCxXaAaol/W38UFHpi0B1kJ4UBiDu81QsH2HKJAacLCrlbRdfS
            XgHg8yJSvDqPWmF4KeJcH4LwFMMZ2ZFi+eZauvdBJbb/Br1ez9eMeVDSq0Qlv+vS
            SSzuQQJI1zSMKj1IBaeaSWQjPfV0/TNLdCmBg1zzrO2F9Jn7/GQenm7lP9OjN8E=
            =LOsb
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(env)$
    version: 3.7.3
