apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 3rd
  namespace: flux-system
spec:
  interval: 60m0s
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./3rd/staging
  prune: true
  wait: true
  timeout: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg