apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: podinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 9898
    # container port number or name (optional)
    targetPort: 9898
  analysis:
    alerts:
      - name: slack
        severity: info
        providerRef:
          name: slack
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    # Linkerd Prometheus checks
    metrics:
    - name: "404s percentage"
      threshold: 3
      query: |
        100 - sum(
            rate(
                response_total{
                    namespace="podinfo",
                    deployment="podinfo",
                    status_code!="404",
                    direction="inbound"
                }[1m]
            )
        )
        /
        sum(
            rate(
                response_total{
                    namespace="podinfo",
                    deployment="podinfo",
                    direction="inbound"
                }[1m]
            )
        )
        * 100     
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      thresholdRange:
        max: 500
      interval: 30s
    # testing (optional)
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://loadtester.flagger/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://podinfo-canary.podinfo:9898/token | grep token"
      # - name: load-test
      #   type: rollout
      #   url: http://loadtester.flagger/
      #   metadata:
      #     cmd: "hey -z 2m -q 10 -c 2 http://podinfo-canary.podinfo:9898/"
      # - name: confirm-rollout-gate
      #   type: confirm-rollout
      #   url: http://loadtester.flagger/gate/approve
      # - name: confirm-traffic-increase-gate
      #   type: confirm-traffic-increase
      #   url: http://loadtester.flagger/gate/approve
      # - name: confirm-promotion-gate
      #   type: confirm-promotion
      #   url: http://loadtester.flagger/gate/approve
      # - name: rollback-gate
      #   type: rollback
      #   url: http://loadtester.flagger/rollback/check
