apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
bases:
  - ../../base/podinfo
  - alert.enc.yaml
  - canary.yaml
patchesStrategicMerge:
  - ingress.enc.yaml
replicas:
- name: podinfo
  count: 0
- name: load
  count: 0