apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencost
resources:
  - namespace.yaml
  - release.yaml
  - secret.yaml
secretGenerator:
  - name: opencost-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
