apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
bases:
  - ../../base/keycloak
patchesStrategicMerge:
  - secret.enc.yaml
  - keycloak.enc.yaml
  - ingress.enc.yaml