apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
type: Opaque
data:
    username: ENC[AES256_GCM,data:fg3sANjzu7F2ukud,iv:Gwbvb3A+nutxniU007l1CLpyiNsZsakQ+qCLZvch4s0=,tag:cbF8mssVrY8f8hZDufl7hA==,type:str]
    password: ENC[AES256_GCM,data:ikECkDyrxW87pxKg,iv:fjXuTParlYwn8W/lfJ1gTKPlBxmB+6XuqxSmHlxi9Lg=,tag:OZkBxHIhhDyiCQx8U5z3ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-14T06:07:03Z"
    mac: ENC[AES256_GCM,data:eHYEgHbD1xEJWrJHzfadxhxQzi4JMgKLtDwdIChWKz7K33JLyqtAb8eptuIS+jXwrQHDevSxysXsHIlHDldlhMTboYJZL2eJiiF7sMuS4uHa95JrV0yp3NVaIBM0xSZbtJcPMQEbY637tMPKAmz30Eb39/n66vEaQJvQgGREtcI=,iv:ekLo0ZTRRrhW+6n/EjrW8wp6KCMSfP6RtcTZRgWpE4E=,tag:Fj+FQLIZCesjnyLcj5XJIw==,type:str]
    pgp:
        - created_at: "2023-02-14T06:07:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA38T7Az157GMARAAw2Uwka23aHGh5XVaXiucEtkKbIAzGJKw6wUwDD8gWNhA
            46MNuojPUSKFmKxqb/nHXX5Gra2DeCfWpuHHFQzmmqMSS/QkImNeRF33sk78zaBz
            7rLqQXEFGMQbX4yfSiYficjRasrHa0djmMXhz1rjswolgMXfWItfm5QvwYASSdxz
            IqvJ1SbllO7l3ZsAAm8BwZJ4chIlpS7aOtwbFUswd2MAGEFfJrtEofR26q3NfvzW
            sDMJxcRZnUpPm1lEDioj2KGBgJJRRgXx2dtbwVcN2nvPqXiapH4o+jYEhGLuSN3E
            DBThQBq8TqeacJoWsgqmIvDgZkUZlZ43pc4MK3+/kylN4MR7i90Zak2b6U36Atb+
            93sgcN/LpjjzINbS0HMn7i67Y+9w3UVzvfB11fSGQ+Usnd1K2igRjoXSgm8Z+av2
            dF6hXzEc+2ItRyHrxrl/6e/oCxRe/yes66p0a7bmgqkCQUlr7lEE0AT+zClPu+BR
            OeH0kYe2ikiJPEmTAgvzheTCLa6QTcdrowQqQb7zFmBYxQXN/z32/81P+a2Bzrpn
            EsR0S8J3kSkgCnpsLl4/URvhaUPpQZY+g6eLpL9hXzu/bvoUWHeSLQS7yxzczRnI
            gxqTX6Z2tnBff+l5Stz0WWcBLSCE9cMkAhJ3U/FljHw67exatPmpCio686EUCi7S
            XgHxA9B8GXPJvvbStc/N0eRa74IPCDkBuSlBHWRJJ2VNQhBMq+9Z4iDZVGfZPWaU
            vdbIzdUOGRKP82owre4QpyUXjdTrDK17mMVNUt/2rUScvdL1VT8RJD+qtbXZHBg=
            =put5
            -----END PGP MESSAGE-----
          fp: 129994A38E40322EE2A4FA6CB59C51DA13B1BF22
    encrypted_regex: ^(host|hosts|hostname|data)$
    version: 3.7.3
