apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - linkerd.yaml
  - linkerd-smi.yaml
  - flagger.yaml
  - prometheus-community.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - oauth2-proxy.yaml
  - grafana.yaml
  - chaos-mesh.yaml
  - botkube.yaml
