apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-demo
spec:
  releaseName: otel-demo
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3