apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb
resources:
  - ../../base/mongodb
secretGenerator:
  - name: mongodb-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
