apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-workload-identity-system
resources:
  - ../../base/azure-workload-identity
secretGenerator:
  - name: workload-identity-webhook-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
