apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo-distributed
resources:
  - ../../base/tempo-distributed
secretGenerator:
  - name: tempo-distributed-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
