apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-jaeger
resources:
  - ../../base/linkerd-jaeger
secretGenerator:
  - name: tempo-values
    behavior: merge
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
