apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-istio
    kind: Issuer
  commonName: REPLACE_ME
  dnsNames:
  - REPLACE_ME