apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
  - namespace.yaml
  - release.yaml
  - secret.yaml
  - issuer.yaml
  - certificate.yaml
  - gateway.yaml
  - authorizationpolicy.yaml
  - monitoring.yaml
secretGenerator:
  - name: istio-ingress-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
