apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      istio: ingress
  namespaceSelector:
    matchNames:
      - istio-ingress
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
