apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
bases:
  - ../../base/flux
patchesStrategicMerge:
  - slack.enc.yaml
  - ingress.enc.yaml
secretGenerator:
  - name: webhook-token
    behavior: merge
    envs:
      - webhook-token.enc.env