apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo
bases:
  - ../../base/bookinfo
resources:
  - virtualservice.enc.yaml
  - destinationrule.yaml
  - virtualservice-v2.yaml
replicas:
- name: details-v1
  count: 0
- name: productpage-v1
  count: 0
- name: ratings-v1
  count: 0
- name: reviews-v1
  count: 0
- name: reviews-v2
  count: 0
- name: reviews-v3
  count: 0  