pilot:
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
global:
  proxy:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
meshConfig:
  extensionProviders:
  - name: "oauth2-proxy"
    envoyExtAuthzHttp:
      service: "oauth2-proxy.oauth2-proxy.svc.cluster.local"
      port: "80"
      includeHeadersInCheck: ["authorization","cookie","x-forwarded-access-token","x-forwarded-user","x-forwarded-email","x-forwarded-proto","proxy-authorization","user-agent","x-forwarded-host","from","x-forwarded-for","accept","x-auth-request-redirect"]
      headersToUpstreamOnAllow: ["authorization","path","cookie","x-auth-request-user","x-auth-request-email","x-auth-request-access-token","x-forwarded-access-token"]
      headersToDownstreamOnDeny: ["content-type","set-cookie"]