apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatgpt-next-web
resources:
  - ../../base/chatgpt-next-web
patchesStrategicMerge:
  - deployment.enc.yaml
  - ingress.enc.yaml
replicas:
- name: chatgpt-next-web
  count: 0