apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
spec:
  releaseName: linkerd-jaeger
  dependsOn:
    - name: linkerd-crds
      namespace: linkerd      
    - name: linkerd-control-plane
      namespace: linkerd
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "30.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tempo-values
