apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
spec:
  releaseName: postgres
  dependsOn:
    - name: prometheus
      namespace: monitoring  
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: postgres-values
