apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - release.yaml
secretGenerator:
  - name: kiali-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
