apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
spec:
  releaseName: botkube
  chart:
    spec:
      chart: botkube
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
      version: "v1.5.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: botkube-values
