apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
spec:
  releaseName: memcached
  dependsOn:
    - name: prometheus
      namespace: monitoring  
  chart:
    spec:
      chart: memcached
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "6.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: memcached-values
