apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  dependsOn:
    - name: prometheus
      namespace: monitoring
    - name: memcached
      namespace: memcached
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.4.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: ingress-nginx-values
