# Default values
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
controller:
  config: 
    global-rate-limit-memcached-host: memcached.memcached.svc.cluster.local
    global-rate-limit-memcached-port: "11211"
    log-format-escape-json: "true"
    use-geoip: "true"
    log-format-upstream:
                  '{
                    "msec": "$msec",
                    "connection": "$connection",
                    "connection_requests": "$connection_requests",
                    "pid": "$pid",
                    "request_id": "$request_id",
                    "request_length": "$request_length",
                    "remote_addr": "$remote_addr",
                    "remote_user": "$remote_user",
                    "remote_port": "$remote_port",
                    "time_local": "$time_local", 
                    "time_iso8601": "$time_iso8601",
                    "request": "$request",
                    "request_uri": "$request_uri",
                    "args": "$args",
                    "status": "$status",
                    "body_bytes_sent": "$body_bytes_sent",
                    "bytes_sent": "$bytes_sent",
                    "http_referer": "$http_referer",
                    "http_user_agent": "$http_user_agent",
                    "http_x_forwarded_for": "$http_x_forwarded_for",
                    "http_host": "$http_host",
                    "server_name": "$server_name",
                    "request_time": "$request_time",
                    "upstream": "$upstream_addr",
                    "upstream_connect_time": "$upstream_connect_time",
                    "upstream_header_time": "$upstream_header_time",
                    "upstream_response_time": "$upstream_response_time",
                    "upstream_response_length": "$upstream_response_length",
                    "upstream_cache_status": "$upstream_cache_status",
                    "ssl_protocol": "$ssl_protocol",
                    "ssl_cipher": "$ssl_cipher",
                    "scheme": "$scheme",
                    "request_method": "$request_method",
                    "server_protocol": "$server_protocol",
                    "pipe": "$pipe",
                    "gzip_ratio": "$gzip_ratio", 
                    "http_cf_ray": "$http_cf_ray",
                    "geoip_country_code": "$geoip_country_code",
                    "http_cookie": "$http_cookie",
                    "global_rate_limit_exceeding": "$global_rate_limit_exceeding"
                  }'
  replicaCount: 2
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
  service:
    externalTrafficPolicy: "Local"
  extraVolumeMounts: 
    - name: modsecurity
      mountPath: /etc/nginx/modsecurity/modsecurity.conf
      subPath: modsecurity.conf
      readOnly: true
  extraVolumes:
    - name: modsecurity
      configMap:
        name: modsecurity      