apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
spec:
  releaseName: chaos-mesh
  chart:
    spec:
      chart: chaos-mesh
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: chaos-mesh-values
