# ./.github/workflows/image-auto-pr.yaml
name: Image Updates Auto-PR
on:
  create:
    branches: ['image-updates']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An Automated PR*"
        pr_reviewer: "huangyingting"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}