apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memcached
resources:
  - ../../base/memcached
configMapGenerator:
  - name: memcached-values
    behavior: merge
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml