# Default values
# https://artifacthub.io/packages/helm/bitnami/memcached
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
resources:
  limits: 
  requests:
    memory: 64Mi
    cpu: 10m
