apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qdrant
spec:
  releaseName: qdrant
  dependsOn:
    - name: prometheus
      namespace: monitoring
  chart:
    spec:
      chart: qdrant
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: qdrant-values
