apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql
resources:
  - ../../base/mysql
secretGenerator:
  - name: mysql-values
    behavior: merge
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
